export default {
  common: {
    termsAndConditions: 'Terms and Conditions',
    iHaveRead: 'I have read and accepted the',
    somethingWrong: 'Something went wrong',
    cannotGetDataFromServer: "Can't get data from the server",
    toAccess: 'Permit the app to access the',
    location: 'location',
    camera: 'camera',
    contacts: 'contacts',
    storage: 'storage',
    microphone: 'microphone',
    gallery: 'gallery',
    files: 'files',
    placeholder: {
      search: 'Search',
    },
    securePassword: 'Your password is protected and secure',
    ok: 'Ok',
    new: 'New',
    outstanding: 'Outstanding',
    needPermissions: 'Need Permissions',
  },
  myAccount: {
    heading: 'My Account',
    update: 'Update',
  },
  myWorkspace: {
    pin: 'Pin',
    seats: 'Seats',
    heading: 'My Workspace',
    modalHeader: 'Are You Sure?',
    modalTitle:
      'Revoking the member from the workspace you remove all his assignments and access to projects. He must be re-invited to enter.',
    modalFirstButtonTitle: 'Yes',
    modalSecondButtonTitle: 'No',
  },
  initialScreen: {
    getStarted: 'Get started',
    terms: 'Terms of use',
    policy: 'Privacy Policy',
    haveAccount: 'Have an account? ',
  },
  createWorkSpace: {
    createWorkSpace: 'Create a workspace',
    placeholder: 'Workspace name',
    requiredError: 'Workspace name is required',
    save: 'Save',
    description:
      'We created a workspace for you.\n' +
      ' You can invite your employees there.',
  },
  noWorkSpace: {
    welcome: 'Welcome to',
    to: 'Align360.',
    name: 'Workspace',
    desc: 'join a workspace and\n see your projects and to-do’s',
    button: 'Join Workspace',
  },
  joinWorkSpace: {
    joinWorkspace: 'Join a workspace',
    join: 'Join',
    pinRequiredError: 'Pin is required',
    workspacePin: 'Workspace PIN',
    onlyNumbers: 'Only numbers',
    iDontHaveAPin: 'I don’t have a PIN',
    signUpTitle: 'Sign up completed',
    signUpDescription:
      'Please log in to the system using your \n' + 'e-mail and password',
    ok: 'Ok',
    enterPin: 'Enter your workspace pin below',
    modalTitle: 'Workspace Added',
    modalHeading: 'Your workspace has been successfully added to your profile.',
  },
  startProject: {
    startProject: 'Start project',
    name: 'Project name',
    address: 'Street address',
    state: 'State',
    zip_code: 'Zip code',
    saveProject: 'Save project',
    create: 'Create',
    project: 'Project',
    later: 'Save for later.',
    skip: 'Skip',
    modalHeading: 'Sign up Completed',
    modalTitle: 'Please log in to the system using your e-mail and password.',
  },

  illustration: {
    firstHeading: 'Welcome To',
    firstDescription:
      'Use Align360 to better organize your construction projects with subcontractors',
    secondHeading: 'Schedule',
    thirdHeading: 'Know Your',
    align: 'Align 360',
    punchLists: 'Punch Lists',
    progress: 'Progress',
  },
  getStarted: {
    next: 'Next',
    heading:
      'Let’s begin,\nare you a contractor,\nsub-contractor,\nor employee?',
    contractor: 'Contractor',
    subContractor: 'Subcontractor',
    employee: 'Employee',
  },
  createAccount: {
    createAccount: 'Create Account',
    createAnAccount: 'Create\nAn Account.',
    namePlaceHolder: 'Full name',
    companyPlaceHolder: 'Name Of Company',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Re-enter Password',
    secureText: 'Your password is protected and secure',
    code: 'Code',
    registerError: 'Registration error',
    position: 'Position',
    phoneNumber: 'Phone Number',
  },
  validRules: {
    emailWrong: 'Wrong email format',
    emailEmpty: 'Email should be filled',
    passwordWrongFormat:
      'Password should be of minimum 6 characters and it should be in alphanumeric format',
    passwordEmpty: 'Please fill all the required fields',
    passwordsNotMatches: 'Passwords do not match',
    userNameEmpty: 'Please, fill in your Full Name',
    wrongUserName: 'Letters only',
    companyNameEmpty: 'Please, fill in your Company Name',
    wrongAboutYourself: 'The information should be 200 characters or less',
    required: 'Field is required',
  },
  forgotPassword: {
    forgotPassword: 'Forgot Password?',
    changePassword: 'Change Password',
    firstDescription:
      'Please enter your email address and we will send you a temporary code',
    send: 'Send',
    emailSent: 'Email Sent',
    modalDescription:
      'Please check your email and follow instructions from the letter.',
    modalDescription2: 'Please log in to the system using new password',
    ok: 'Ok',
    code: 'Code ',
    newPassword: 'New password',
    reEnterPassword: 'Re-enter password',
    confirm: 'Confirm',
    required: 'Field is required',
    actionPerformed: 'Action performed',
    step2: 'Step 2',
  },
  drawer: {
    logout: 'Logout',
    settings: 'Settings',
  },
  tabs: {
    home: 'Home',
    projects: 'Projects',
  },
  room: {
    add: 'Add',
    edit: 'Edit',
    room: 'Room',
    label: 'Room Name',
    placeholder: 'Room Goes Here',
    saveRoom: 'Save',
    updateRoom: 'Update',
    createPhotoHere: 'Create photos here add task hotspots',
    addPhotoPlaceholder:
      'Tap to add photos of your room and add task hotspots.',
    static: {
      title: 'Album',
      subtitle: 'Tap on image to preview and add task hotspots.',
    },
    '360': {
      title: 'Album',
      subtitle: 'Tap on image to preview and add task hotspots.',
    },
    title: 'Project Name',
    addMarker: 'Add Marker',
    actionSheet: {
      edit: 'Edit Room',
      archive: 'Archive Room',
      delete: 'Delete Room',
    },
  },
  signIn: {
    signIn: 'Sign in',
    skip: 'Skip',
    login: 'Login',
    newAccount: ' New Account',
    forgotPassword: 'Forgot password',
  },
  messages: {
    heading: 'Align 360',
    title: 'Messages',
    newMessage: 'New Messages',
    noMessages: 'No Messages',
    tapeHere: 'Tap here to create new message.',
    maxSize: '0 / 1000 [ Limited to a 1000 Characters ]',
    searchPlaceholder: 'Type a name',
    suggested: 'Suggested:',
  },
  termsScreen: {
    termsAndConditions: 'Terms\nAnd Conditions',
    privacyPolicy: 'Privacy Policy',
  },
  imageViewerScreen: {
    addMarker: 'Tap anywhere to add marker',
    moveMarker: '[ Move marker to desired location ]',
    applyMarker: 'Confirm',
  },
  homeScreen: {
    yourProjects: 'Your Projects',
    noProjects: 'You currently have no projects',
    todaysBrief: "Today's Brief",
    noBrief: 'No data',
    yourMessages: 'Messages',
    noMessages: 'You currently have no messages',
    toDo: 'To-Do List',
    materials: 'Materials',
    tools: 'Tools',
    counterLabel: 'Projects',
    new: 'New',
    outstanding: 'Outstanding',
  },
  settings: {
    heading: 'Settings',
    myWorkspace: 'My Workspace',
    myAccount: 'My Account',
    changePassword: 'Change Password',
  },
  changePassword: {
    oldPassword: 'Old Password',
    reEnterNewPassword: 'Re-enter New Password',
    success: 'Success!',
    description: 'Your password was successfully changed.',
  },
  actionSheet: {
    uploadPhoto: {
      title: 'Upload Photo',
    },
    delete: {
      title: 'Delete Photo',
    },
  },
  inviteMembers: {
    header: 'Invite Members',
    title: 'Invite employees to connect your Workspace.',
  },
  projects: {
    title: 'Your Projects',
    placeholder: {
      title: 'No Projects',
      text: 'You currently have no projects',
    },
  },
  project: {
    rooms: {
      title: 'Rooms',
      placeholder: {
        title: '[ Tap the “+” to Add ]',
        text: 'You currently don’t have a room.',
      },
    },
    trade: {
      title: 'Trade To-Do',
      placeholder: {
        title: '[ Tap the “+” to Add ]',
        text: 'You currently don’t have any Trade To-Do’s.',
      },
    },
    materials: {
      title: 'Materials and Tools',
      placeholder: {
        title: '[ Tap the “+” to Add ]',
        text: 'You currently don’t have any Materials and Tools.',
      },
    },
    modal: {
      actions: {
        title: 'Actions',
        firstList: [
          'New Punchlist Item',
          'New Room',
          'New Trade',
          'New Material or Tool',
        ],
        secondList: ['Edit Project', 'Archive Project', 'Delete Project'],
      },
      delete: {
        title: 'Delete Project',
        text: 'Do you realy want to delete project?',
        buttons: {
          cancel: 'Cancel',
          delete: 'Delete',
        },
      },
      tool: {
        title: 'New Tool',
        type: 'Tool Type',
        buttonTitle: 'Add',
      },
    },
  },
  workspaceDetails: {
    leaveWorkspace: 'Leave Workspace',
    workspace: 'Workspace',
    itemToComplete: 'Items to Complete',
    changeOrders: 'Change Orders',
    members: 'Members',
    modalTitle:
      'Leaving this workspace will remove all assignments and access to projects. You must be re-invited to enter.',
    yes: 'Yes',
    no: 'No',
  },
  addPunchList: {
    title: 'Punchlist Item',
    changeAssigneeTitle: 'Change Assignment',
    changeAssigneeButtonTitle: 'Update assignee',
    titleLabel: 'Add',
    edit: 'Edit',
    actionSheetTitle: 'Upload File',
    uploadFilePlaceholder: 'Tap here to upload file',
    dateModal: {
      title: 'Select Date',
    },
    form: {
      trade: 'Trade Type',
      task: 'Name of Task',
      hours: 'Estimated Completion',
      priority: 'Task Priority',
      room: 'Room Location',
      dueDate: 'Due Date',
      assignee: 'Assignee',
      changeOrder: 'Change Order',
      description: 'Project Brief',
      file: 'File Upload',
    },
    modal: {
      delete: {
        title: 'This action will delete the punchitem and all connected files',
        subTitle: 'Are you sure',
      },
      archive: {
        title: 'This action will not delete the punchitem and all connected files. It will be removed to Archive.',
        subTitle: 'Are you sure',
      },
      buttons: {
        delete: 'Delete',
        notDelete: 'Not Delete',
        archive: 'Archive',
        notArchive: 'Not Archive',
      },
    },
  },
};
